# Generated by Django 3.2.13 on 2022-05-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cProjectname', models.CharField(max_length=20)),
                ('cCusetername', models.CharField(max_length=20)),
                ('cProjectcode', models.DateField(max_length=20)),
                ('cLocation', models.DateField(default='', max_length=100)),
                ('cContent', models.DateField(default='', max_length=100)),
                ('cLastproject', models.DateField(default='', max_length=100)),
                ('cAbility', models.DateField(default='', max_length=100)),
                ('cType', models.DateField(default='', max_length=100)),
                ('cCotpye', models.DateField(default='', max_length=100)),
                ('cProjecttype', models.DateField(default='', max_length=100)),
                ('cStage', models.DateField(default='', max_length=100)),
                ('cNoted', models.DateField(default='', max_length=100)),
            ],
        ),
    ]
