# Generated by Django 3.2.13 on 2022-05-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_requisition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='cAbility',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='cContent',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='cCotpye',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='cLastproject',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='cLocation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='cNoted',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='cProjectcode',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='cProjecttype',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='cStage',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='cType',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='cBirthday',
            field=models.DateTimeField(),
        ),
    ]
