# Generated by Django 4.0.6 on 2022-07-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_requisition_cability'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='cdatestart',
            field=models.DateField(default=''),
        ),
    ]
