# Generated by Django 4.0.6 on 2022-07-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_requisition_cdatestart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='cdatestart',
            field=models.DateField(blank=True, null=True),
        ),
    ]
