# Generated by Django 4.0.6 on 2022-07-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_requisition_cdatestart'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='cdateend',
            field=models.DateField(blank=True, null=True),
        ),
    ]
