# Generated by Django 4.0.6 on 2022-07-20 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_requisition_cdateend_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='cdateend',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='cdatestart',
        ),
    ]
