# Generated by Django 4.0.6 on 2022-07-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_requisition_cdateend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='cFunction',
            field=models.CharField(default='', max_length=20),
        ),
    ]
