# Generated by Django 4.0.6 on 2022-07-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_requisition_cfunction'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='cFunction',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='requisition',
            name='cdateend',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='cdatestart',
            field=models.DateField(blank=True, null=True),
        ),
    ]
