# Generated by Django 4.0.6 on 2022-07-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_requisition_datetimeofupload_requisition_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='uploadedFile',
            field=models.FileField(upload_to='documents/%Y/%m/%d'),
        ),
    ]
