# Generated by Django 4.0.6 on 2022-07-21 09:50

from django.db import migrations
import myapp.formatChecker


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_requisition_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='uploadedFile',
            field=myapp.formatChecker.ContentTypeRestrictedFileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
