# Generated by Django 4.0.6 on 2022-07-24 04:42

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_requisition_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='uploadedFile',
            field=models.FileField(default='', upload_to=myapp.models.user_directory_path),
        ),
    ]
