# Generated by Django 4.0.6 on 2022-07-24 05:13

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_requisition_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='uploadedFile',
            field=models.FileField(blank=True, default='', upload_to=myapp.models.user_directory_path),
        ),
    ]
