# Generated by Django 4.0.6 on 2022-07-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_requisition_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='clereply_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(default='', max_length=50)),
                ('checklist', models.CharField(default='', max_length=50)),
                ('producttype', models.CharField(default='', max_length=50)),
                ('productscoreline', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
