# Generated by Django 4.0.6 on 2022-09-22 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_requisition_cstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='cStatus',
        ),
    ]
