# Generated by Django 4.0.6 on 2022-09-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_remove_requisition_cstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='cStatus',
            field=models.CharField(default='In Progress', max_length=20),
        ),
    ]
