# Generated by Django 4.0.6 on 2022-09-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_requisition_cstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cName', models.CharField(max_length=10)),
                ('cVotenumber', models.CharField(max_length=30)),
                ('cVotetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='requisition',
            name='cLastproject',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='cNoted',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='cProjecttype',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='cSchedule',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='cSpecial',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
