# Generated by Django 4.0.6 on 2022-09-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_vote_alter_requisition_clastproject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='cVoteselect',
            field=models.BooleanField(default=False),
        ),
    ]
