# Generated by Django 4.0.6 on 2022-09-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_vote_cvoteselect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='cVoteselect',
            field=models.BooleanField(default=False),
        ),
    ]
