# Generated by Django 4.0.6 on 2022-09-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_alter_vote_cvotenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='cVotenumber',
            field=models.CharField(max_length=30),
        ),
    ]
