# Generated by Django 4.0.6 on 2022-10-03 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_remove_vote_cvotenumber_requisition_cvotename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='cVotename',
        ),
    ]
