# Generated by Django 4.0.6 on 2022-10-06 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_addressinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressInfo3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=30, null=True, verbose_name='Function')),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.addressinfo3', verbose_name='自關聯')),
            ],
        ),
        migrations.CreateModel(
            name='AddressInfo2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=30, null=True, verbose_name='Function')),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.addressinfo2', verbose_name='自關聯')),
            ],
        ),
        migrations.CreateModel(
            name='AddressInfo1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=30, null=True, verbose_name='Function')),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.addressinfo1', verbose_name='自關聯')),
            ],
        ),
    ]
