# Generated by Django 4.0.6 on 2022-10-12 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_addressinfo3_addressinfo2_addressinfo1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressinfo2',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='addressinfo3',
            name='pid',
        ),
        migrations.DeleteModel(
            name='AddressInfo1',
        ),
        migrations.DeleteModel(
            name='AddressInfo2',
        ),
        migrations.DeleteModel(
            name='AddressInfo3',
        ),
    ]
