# Generated by Django 4.0.6 on 2022-10-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_remove_addressinfo2_pid_remove_addressinfo3_pid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='addressinfo',
            name='publications',
            field=models.ManyToManyField(to='myapp.person'),
        ),
    ]
