# Generated by Django 4.0.6 on 2022-10-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_person_addressinfo_publications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Person',
            new_name='Type',
        ),
        migrations.AddField(
            model_name='addressinfo',
            name='publications2',
            field=models.ManyToManyField(to='myapp.type2'),
        ),
    ]
