# Generated by Django 4.0.6 on 2022-11-01 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_alter_type_name_alter_type2_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='worktype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Worktype_number', models.IntegerField()),
                ('Worktype_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='addressinfo',
            name='pid',
        ),
        migrations.AlterField(
            model_name='addressinfo',
            name='publications',
            field=models.ManyToManyField(blank=True, default='', to='myapp.type'),
        ),
        migrations.AlterField(
            model_name='addressinfo',
            name='publications2',
            field=models.ManyToManyField(blank=True, default='', to='myapp.type2'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='type2',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bigcate', models.CharField(max_length=50)),
                ('catid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.worktype')),
            ],
            options={
                'db_table': 'my_category',
                'unique_together': {('catid', 'bigcate')},
            },
        ),
    ]
