# Generated by Django 4.0.6 on 2022-11-01 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_worktype_remove_addressinfo_pid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='worktype',
        ),
    ]
