# Generated by Django 4.0.6 on 2022-11-01 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_delete_category_delete_worktype'),
    ]

    operations = [
        migrations.CreateModel(
            name='worktype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Worktype_number', models.IntegerField()),
                ('Worktype_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Category3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bigcate', models.CharField(max_length=50)),
                ('Category_name', models.CharField(max_length=50)),
                ('Catid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.worktype')),
            ],
            options={
                'db_table': 'my_category3',
                'unique_together': {('Catid', 'Bigcate')},
            },
        ),
        migrations.CreateModel(
            name='Category2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bigcate', models.CharField(max_length=50)),
                ('Category_name', models.CharField(max_length=50)),
                ('Catid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.worktype')),
            ],
            options={
                'db_table': 'my_category2',
                'unique_together': {('Catid', 'Bigcate')},
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bigcate', models.CharField(max_length=50)),
                ('Category_name', models.CharField(max_length=50)),
                ('Catid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.worktype')),
            ],
            options={
                'db_table': 'my_category',
                'unique_together': {('Catid', 'Bigcate')},
            },
        ),
    ]
