# Generated by Django 4.0.6 on 2022-11-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_worktype_category3_category2_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Bigcate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='category2',
            name='Bigcate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='category3',
            name='Bigcate',
            field=models.IntegerField(),
        ),
    ]
