# Generated by Django 4.0.6 on 2022-11-03 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_alter_category_bigcate_alter_category2_bigcate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Category_name',
            new_name='categoryname',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='Catid',
            new_name='catid',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='Bigcate',
            new_name='worktypename',
        ),
        migrations.RenameField(
            model_name='category2',
            old_name='Category_name',
            new_name='categoryname',
        ),
        migrations.RenameField(
            model_name='category2',
            old_name='Catid',
            new_name='catid',
        ),
        migrations.RenameField(
            model_name='category2',
            old_name='Bigcate',
            new_name='worktypename',
        ),
        migrations.RenameField(
            model_name='category3',
            old_name='Category_name',
            new_name='categoryname',
        ),
        migrations.RenameField(
            model_name='category3',
            old_name='Catid',
            new_name='catid',
        ),
        migrations.RenameField(
            model_name='category3',
            old_name='Bigcate',
            new_name='worktypename',
        ),
        migrations.RenameField(
            model_name='worktype',
            old_name='Worktype_name',
            new_name='worktypename',
        ),
        migrations.RenameField(
            model_name='worktype',
            old_name='Worktype_number',
            new_name='worktypenumber',
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('catid', 'worktypename')},
        ),
        migrations.AlterUniqueTogether(
            name='category2',
            unique_together={('catid', 'worktypename')},
        ),
        migrations.AlterUniqueTogether(
            name='category3',
            unique_together={('catid', 'worktypename')},
        ),
    ]
