# Generated by Django 4.0.6 on 2022-11-03 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_rename_category_name_category_categoryname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='catid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='worktypename',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.worktype'),
        ),
        migrations.AlterField(
            model_name='category2',
            name='catid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='category2',
            name='worktypename',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.worktype'),
        ),
        migrations.AlterField(
            model_name='category3',
            name='catid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='category3',
            name='worktypename',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.worktype'),
        ),
    ]
